export interface Word {
  word: string;
  reading: string;
  meaning: string;
  example: string;
  example_en: string;
}

export interface Topic {
  key: string;
  emoji: string;
  title: string;
  words: Word[];
}

export const TOPICS: Topic[] = [
  {
    key: 'konbini', emoji: '🏪', title: 'Konbini',
    words: [
      { word: 'レジ', reading: 'reji', meaning: 'cash register', example: 'レジはどこですか？', example_en: 'Where is the register?' },
      { word: '温める', reading: 'あたためる', meaning: 'to heat up', example: '温めますか？', example_en: 'Shall I heat it up?' },
      { word: '袋', reading: 'ふくろ', meaning: 'bag', example: '袋はいりますか？', example_en: 'Do you need a bag?' },
      { word: 'お弁当', reading: 'おべんとう', meaning: 'boxed lunch', example: 'お弁当を一つください。', example_en: 'One boxed lunch, please.' },
      { word: 'おにぎり', reading: 'おにぎり', meaning: 'rice ball', example: 'おにぎりは何味がありますか？', example_en: 'What flavors of rice balls do you have?' },
      { word: 'お箸', reading: 'おはし', meaning: 'chopsticks', example: 'お箸をつけてください。', example_en: 'Please include chopsticks.' },
      { word: 'ポイントカード', reading: 'pointo kādo', meaning: 'point card', example: 'ポイントカードはお持ちですか？', example_en: 'Do you have a point card?' },
      { word: '電子マネー', reading: 'でんしまねー', meaning: 'digital money', example: '電子マネーで払えますか？', example_en: 'Can I pay with digital money?' },
      { word: 'コピー機', reading: 'こぴーき', meaning: 'copy machine', example: 'コピー機はありますか？', example_en: 'Do you have a copy machine?' },
      { word: 'ATM', reading: 'ētiemu', meaning: 'ATM', example: 'ATMはどこですか？', example_en: 'Where is the ATM?' },
      { word: 'トイレ', reading: 'toire', meaning: 'toilet/restroom', example: 'トイレを借りてもいいですか？', example_en: 'May I use the restroom?' },
      { word: '領収書', reading: 'りょうしゅうしょ', meaning: 'receipt', example: '領収書をお願いします。', example_en: 'Receipt, please.' },
      { word: '現金', reading: 'げんきん', meaning: 'cash', example: '現金のみですか？', example_en: 'Is it cash only?' },
      { word: 'スプーン', reading: 'supūn', meaning: 'spoon', example: 'スプーンをください。', example_en: 'Please give me a spoon.' },
      { word: 'ストロー', reading: 'sutorō', meaning: 'straw', example: 'ストローはいりますか？', example_en: 'Do you need a straw?' },
    ],
  },
  {
    key: 'bank', emoji: '🏦', title: 'Bank & ATM',
    words: [
      { word: '振込', reading: 'ふりこみ', meaning: 'bank transfer', example: '振込をしたいです。', example_en: 'I want to make a transfer.' },
      { word: '口座', reading: 'こうざ', meaning: 'bank account', example: '口座を開きたいです。', example_en: 'I want to open an account.' },
      { word: '残高', reading: 'ざんだか', meaning: 'balance', example: '残高を確認したいです。', example_en: 'I want to check my balance.' },
      { word: '引き出し', reading: 'ひきだし', meaning: 'withdrawal', example: '引き出しをお願いします。', example_en: 'I want to make a withdrawal.' },
      { word: '預金', reading: 'よきん', meaning: 'deposit', example: '預金をしたいです。', example_en: 'I want to make a deposit.' },
      { word: '暗証番号', reading: 'あんしょうばんごう', meaning: 'PIN number', example: '暗証番号を入力してください。', example_en: 'Please enter your PIN.' },
      { word: '通帳', reading: 'つうちょう', meaning: 'bankbook', example: '通帳を記帳したいです。', example_en: 'I want to update my bankbook.' },
      { word: '手数料', reading: 'てすうりょう', meaning: 'fee/commission', example: '手数料はいくらですか？', example_en: 'What is the fee?' },
      { word: 'キャッシュカード', reading: 'kyasshu kādo', meaning: 'cash card', example: 'キャッシュカードを忘れました。', example_en: 'I forgot my cash card.' },
      { word: '送金', reading: 'そうきん', meaning: 'remittance', example: '海外送金はできますか？', example_en: 'Can I send money overseas?' },
      { word: '利息', reading: 'りそく', meaning: 'interest', example: '利息はどのくらいですか？', example_en: 'What is the interest rate?' },
      { word: '印鑑', reading: 'いんかん', meaning: 'seal/stamp', example: '印鑑が必要ですか？', example_en: 'Do I need a seal?' },
      { word: '窓口', reading: 'まどぐち', meaning: 'counter/window', example: '窓口で手続きしてください。', example_en: 'Please process it at the counter.' },
      { word: '振込先', reading: 'ふりこみさき', meaning: 'transfer destination', example: '振込先を入力してください。', example_en: 'Please enter the transfer destination.' },
      { word: '両替', reading: 'りょうがえ', meaning: 'currency exchange', example: '両替はできますか？', example_en: 'Can I exchange currency?' },
    ],
  },
  {
    key: 'hospital', emoji: '🏥', title: 'Doctor & Hospital',
    words: [
      { word: '診察', reading: 'しんさつ', meaning: 'medical examination', example: '診察をお願いします。', example_en: 'I would like an examination.' },
      { word: '保険証', reading: 'ほけんしょう', meaning: 'insurance card', example: '保険証をお持ちですか？', example_en: 'Do you have your insurance card?' },
      { word: '症状', reading: 'しょうじょう', meaning: 'symptoms', example: '症状を教えてください。', example_en: 'Please tell me your symptoms.' },
      { word: '薬', reading: 'くすり', meaning: 'medicine', example: '薬をもらえますか？', example_en: 'Can I get medicine?' },
      { word: '処方箋', reading: 'しょほうせん', meaning: 'prescription', example: '処方箋をお願いします。', example_en: 'Prescription, please.' },
      { word: '熱', reading: 'ねつ', meaning: 'fever', example: '熱があります。', example_en: 'I have a fever.' },
      { word: '頭痛', reading: 'ずつう', meaning: 'headache', example: '頭痛がひどいです。', example_en: 'I have a bad headache.' },
      { word: '腹痛', reading: 'ふくつう', meaning: 'stomachache', example: '腹痛があります。', example_en: 'I have a stomachache.' },
      { word: 'アレルギー', reading: 'arerugī', meaning: 'allergy', example: 'アレルギーはありますか？', example_en: 'Do you have any allergies?' },
      { word: '予約', reading: 'よやく', meaning: 'appointment', example: '予約が必要ですか？', example_en: 'Do I need an appointment?' },
      { word: '受付', reading: 'うけつけ', meaning: 'reception', example: '受付で記入してください。', example_en: 'Please fill out forms at reception.' },
      { word: '血圧', reading: 'けつあつ', meaning: 'blood pressure', example: '血圧を測りましょう。', example_en: 'Let me take your blood pressure.' },
      { word: '注射', reading: 'ちゅうしゃ', meaning: 'injection/shot', example: '注射が必要です。', example_en: 'You need an injection.' },
      { word: '入院', reading: 'にゅういん', meaning: 'hospitalization', example: '入院が必要ですか？', example_en: 'Do I need to be hospitalized?' },
      { word: '痛い', reading: 'いたい', meaning: 'painful/hurts', example: 'ここが痛いです。', example_en: 'It hurts here.' },
    ],
  },
  {
    key: 'housing', emoji: '🏠', title: 'Landlord & Housing',
    words: [
      { word: '家賃', reading: 'やちん', meaning: 'rent', example: '家賃はいくらですか？', example_en: 'How much is the rent?' },
      { word: '敷金', reading: 'しききん', meaning: 'security deposit', example: '敷金は一ヶ月分です。', example_en: 'The deposit is one month.' },
      { word: '礼金', reading: 'れいきん', meaning: 'key money', example: '礼金なしの物件はありますか？', example_en: 'Are there properties without key money?' },
      { word: '管理費', reading: 'かんりひ', meaning: 'maintenance fee', example: '管理費は含まれていますか？', example_en: 'Is the maintenance fee included?' },
      { word: '契約', reading: 'けいやく', meaning: 'contract', example: '契約は二年間です。', example_en: 'The contract is for two years.' },
      { word: '更新', reading: 'こうしん', meaning: 'renewal', example: '契約の更新はいつですか？', example_en: 'When is the contract renewal?' },
      { word: '間取り', reading: 'まどり', meaning: 'floor plan', example: '間取りを見せてください。', example_en: 'Please show me the floor plan.' },
      { word: '保証人', reading: 'ほしょうにん', meaning: 'guarantor', example: '保証人が必要ですか？', example_en: 'Do I need a guarantor?' },
      { word: '退去', reading: 'たいきょ', meaning: 'moving out', example: '退去の一ヶ月前に連絡してください。', example_en: 'Please notify one month before moving out.' },
      { word: '鍵', reading: 'かぎ', meaning: 'key', example: '鍵を受け取りたいです。', example_en: 'I want to pick up the keys.' },
      { word: 'ペット可', reading: 'ぺっとか', meaning: 'pets allowed', example: 'ペット可の物件を探しています。', example_en: 'I am looking for pet-friendly properties.' },
      { word: '駅近', reading: 'えきちか', meaning: 'near station', example: '駅近の物件がいいです。', example_en: 'I prefer a property near the station.' },
      { word: '大家', reading: 'おおや', meaning: 'landlord', example: '大家さんに連絡してください。', example_en: 'Please contact the landlord.' },
      { word: '不動産', reading: 'ふどうさん', meaning: 'real estate', example: '不動産屋に行きましょう。', example_en: 'Let us go to the real estate agency.' },
      { word: '光熱費', reading: 'こうねつひ', meaning: 'utility bills', example: '光熱費は別ですか？', example_en: 'Are utilities separate?' },
    ],
  },
  {
    key: 'restaurant', emoji: '🍜', title: 'Restaurant & Ordering',
    words: [
      { word: 'メニュー', reading: 'menyū', meaning: 'menu', example: 'メニューを見せてください。', example_en: 'Please show me the menu.' },
      { word: '注文', reading: 'ちゅうもん', meaning: 'order', example: '注文をお願いします。', example_en: 'I would like to order.' },
      { word: 'お会計', reading: 'おかいけい', meaning: 'bill/check', example: 'お会計をお願いします。', example_en: 'Check, please.' },
      { word: '食券', reading: 'しょっけん', meaning: 'meal ticket', example: '食券を買ってください。', example_en: 'Please buy a meal ticket.' },
      { word: 'おすすめ', reading: 'おすすめ', meaning: 'recommendation', example: 'おすすめは何ですか？', example_en: 'What do you recommend?' },
      { word: '大盛り', reading: 'おおもり', meaning: 'large portion', example: '大盛りにしてください。', example_en: 'Large portion, please.' },
      { word: '持ち帰り', reading: 'もちかえり', meaning: 'takeout', example: '持ち帰りでお願いします。', example_en: 'Takeout, please.' },
      { word: 'アレルギー対応', reading: 'arerugī taiō', meaning: 'allergy friendly', example: 'アレルギー対応メニューはありますか？', example_en: 'Do you have an allergy-friendly menu?' },
      { word: '飲み放題', reading: 'のみほうだい', meaning: 'all-you-can-drink', example: '飲み放題はありますか？', example_en: 'Do you have all-you-can-drink?' },
      { word: '食べ放題', reading: 'たべほうだい', meaning: 'all-you-can-eat', example: '食べ放題のコースをお願いします。', example_en: 'All-you-can-eat course, please.' },
      { word: '禁煙', reading: 'きんえん', meaning: 'no smoking', example: '禁煙席をお願いします。', example_en: 'Non-smoking seat, please.' },
      { word: '席', reading: 'せき', meaning: 'seat', example: '席は空いていますか？', example_en: 'Are there seats available?' },
      { word: 'お水', reading: 'おみず', meaning: 'water', example: 'お水をください。', example_en: 'Water, please.' },
      { word: '辛い', reading: 'からい', meaning: 'spicy', example: 'これは辛いですか？', example_en: 'Is this spicy?' },
      { word: '別々', reading: 'べつべつ', meaning: 'separate (bills)', example: '別々でお願いします。', example_en: 'Separate checks, please.' },
    ],
  },
  {
    key: 'train', emoji: '🚃', title: 'Train & Station',
    words: [
      { word: '切符', reading: 'きっぷ', meaning: 'ticket', example: '切符を買いたいです。', example_en: 'I want to buy a ticket.' },
      { word: '改札', reading: 'かいさつ', meaning: 'ticket gate', example: '改札はどこですか？', example_en: 'Where is the ticket gate?' },
      { word: 'ホーム', reading: 'hōmu', meaning: 'platform', example: '何番ホームですか？', example_en: 'Which platform?' },
      { word: '乗り換え', reading: 'のりかえ', meaning: 'transfer', example: '乗り換えが必要ですか？', example_en: 'Do I need to transfer?' },
      { word: '出口', reading: 'でぐち', meaning: 'exit', example: '東出口はどこですか？', example_en: 'Where is the east exit?' },
      { word: '入口', reading: 'いりぐち', meaning: 'entrance', example: '入口はあちらです。', example_en: 'The entrance is that way.' },
      { word: '定期券', reading: 'ていきけん', meaning: 'commuter pass', example: '定期券を買いたいです。', example_en: 'I want to buy a commuter pass.' },
      { word: '終電', reading: 'しゅうでん', meaning: 'last train', example: '終電は何時ですか？', example_en: 'What time is the last train?' },
      { word: '各駅停車', reading: 'かくえきていしゃ', meaning: 'local train', example: '各駅停車に乗ってください。', example_en: 'Take the local train.' },
      { word: '急行', reading: 'きゅうこう', meaning: 'express', example: '急行は止まりますか？', example_en: 'Does the express stop here?' },
      { word: '遅延', reading: 'ちえん', meaning: 'delay', example: '電車が遅延しています。', example_en: 'The train is delayed.' },
      { word: '片道', reading: 'かたみち', meaning: 'one way', example: '片道でお願いします。', example_en: 'One way, please.' },
      { word: '往復', reading: 'おうふく', meaning: 'round trip', example: '往復切符をください。', example_en: 'A round trip ticket, please.' },
      { word: '指定席', reading: 'していせき', meaning: 'reserved seat', example: '指定席を予約したいです。', example_en: 'I want to reserve a seat.' },
      { word: '運賃', reading: 'うんちん', meaning: 'fare', example: '運賃はいくらですか？', example_en: 'What is the fare?' },
    ],
  },
  {
    key: 'postoffice', emoji: '📮', title: 'Post Office',
    words: [
      { word: '郵便', reading: 'ゆうびん', meaning: 'mail/postal', example: '郵便を出したいです。', example_en: 'I want to send mail.' },
      { word: '切手', reading: 'きって', meaning: 'stamp', example: '切手を買いたいです。', example_en: 'I want to buy stamps.' },
      { word: '荷物', reading: 'にもつ', meaning: 'package', example: '荷物を送りたいです。', example_en: 'I want to send a package.' },
      { word: '速達', reading: 'そくたつ', meaning: 'express mail', example: '速達でお願いします。', example_en: 'Express mail, please.' },
      { word: '書留', reading: 'かきとめ', meaning: 'registered mail', example: '書留で送ってください。', example_en: 'Please send it by registered mail.' },
      { word: '国際便', reading: 'こくさいびん', meaning: 'international mail', example: '国際便はいくらですか？', example_en: 'How much is international mail?' },
      { word: '宛先', reading: 'あてさき', meaning: 'recipient address', example: '宛先を書いてください。', example_en: 'Please write the recipient address.' },
      { word: '差出人', reading: 'さしだしにん', meaning: 'sender', example: '差出人の住所を記入してください。', example_en: 'Please fill in the sender address.' },
      { word: '届ける', reading: 'とどける', meaning: 'to deliver', example: 'いつ届きますか？', example_en: 'When will it be delivered?' },
      { word: '不在票', reading: 'ふざいひょう', meaning: 'missed delivery slip', example: '不在票が入っていました。', example_en: 'There was a missed delivery slip.' },
      { word: '再配達', reading: 'さいはいたつ', meaning: 'redelivery', example: '再配達をお願いします。', example_en: 'Please redeliver.' },
      { word: '小包', reading: 'こづつみ', meaning: 'parcel', example: '小包を受け取りたいです。', example_en: 'I want to pick up a parcel.' },
      { word: '重さ', reading: 'おもさ', meaning: 'weight', example: '重さを量ってください。', example_en: 'Please weigh it.' },
      { word: '追跡番号', reading: 'ついせきばんごう', meaning: 'tracking number', example: '追跡番号を教えてください。', example_en: 'Please give me the tracking number.' },
      { word: 'はがき', reading: 'はがき', meaning: 'postcard', example: 'はがきを五枚ください。', example_en: 'Five postcards, please.' },
    ],
  },
  {
    key: 'government', emoji: '🏢', title: 'City Hall & Gov',
    words: [
      { word: '住民票', reading: 'じゅうみんひょう', meaning: 'resident certificate', example: '住民票が欲しいです。', example_en: 'I need a resident certificate.' },
      { word: '転入届', reading: 'てんにゅうとどけ', meaning: 'moving-in notification', example: '転入届を出したいです。', example_en: 'I want to submit a moving-in form.' },
      { word: '転出届', reading: 'てんしゅつとどけ', meaning: 'moving-out notification', example: '転出届を出す必要があります。', example_en: 'I need to submit a moving-out form.' },
      { word: '在留カード', reading: 'ざいりゅうかーど', meaning: 'residence card', example: '在留カードを見せてください。', example_en: 'Please show your residence card.' },
      { word: '国民健康保険', reading: 'こくみんけんこうほけん', meaning: 'national health insurance', example: '国民健康保険に加入したいです。', example_en: 'I want to enroll in national health insurance.' },
      { word: '申請書', reading: 'しんせいしょ', meaning: 'application form', example: '申請書に記入してください。', example_en: 'Please fill out the application form.' },
      { word: '届出', reading: 'とどけで', meaning: 'notification/report', example: '届出はどこですか？', example_en: 'Where do I submit the notification?' },
      { word: '証明書', reading: 'しょうめいしょ', meaning: 'certificate', example: '証明書を発行してください。', example_en: 'Please issue a certificate.' },
      { word: '窓口', reading: 'まどぐち', meaning: 'service counter', example: '三番窓口に行ってください。', example_en: 'Please go to counter three.' },
      { word: '番号札', reading: 'ばんごうふだ', meaning: 'number ticket', example: '番号札を取ってください。', example_en: 'Please take a number ticket.' },
      { word: '印鑑証明', reading: 'いんかんしょうめい', meaning: 'seal certificate', example: '印鑑証明が必要です。', example_en: 'I need a seal certificate.' },
      { word: '年金', reading: 'ねんきん', meaning: 'pension', example: '年金の手続きをしたいです。', example_en: 'I want to process my pension.' },
      { word: '税金', reading: 'ぜいきん', meaning: 'taxes', example: '税金の相談がしたいです。', example_en: 'I want to consult about taxes.' },
      { word: 'マイナンバー', reading: 'mainanbā', meaning: 'My Number (ID)', example: 'マイナンバーカードを申請したいです。', example_en: 'I want to apply for a My Number card.' },
      { word: '婚姻届', reading: 'こんいんとどけ', meaning: 'marriage registration', example: '婚姻届を出したいです。', example_en: 'I want to submit a marriage registration.' },
    ],
  },
  {
    key: 'business', emoji: '💼', title: 'Business Japanese',
    words: [
      { word: 'お疲れ様です', reading: 'おつかれさまです', meaning: 'good work (greeting)', example: 'お疲れ様です。今日もよろしくお願いします。', example_en: 'Good work. Looking forward to working with you today.' },
      { word: '名刺', reading: 'めいし', meaning: 'business card', example: '名刺を交換しましょう。', example_en: 'Let us exchange business cards.' },
      { word: '会議', reading: 'かいぎ', meaning: 'meeting', example: '会議は何時からですか？', example_en: 'What time does the meeting start?' },
      { word: '報告', reading: 'ほうこく', meaning: 'report', example: '報告書を提出してください。', example_en: 'Please submit the report.' },
      { word: '承知しました', reading: 'しょうちしました', meaning: 'understood (formal)', example: '承知しました。すぐに対応します。', example_en: 'Understood. I will handle it right away.' },
      { word: '失礼します', reading: 'しつれいします', meaning: 'excuse me (formal)', example: '失礼します。お先に帰ります。', example_en: 'Excuse me. I am leaving first.' },
      { word: '確認', reading: 'かくにん', meaning: 'confirmation', example: '確認させてください。', example_en: 'Let me confirm.' },
      { word: '締め切り', reading: 'しめきり', meaning: 'deadline', example: '締め切りはいつですか？', example_en: 'When is the deadline?' },
      { word: '打ち合わせ', reading: 'うちあわせ', meaning: 'meeting/discussion', example: '打ち合わせの時間を決めましょう。', example_en: 'Let us decide the meeting time.' },
      { word: 'ご検討', reading: 'ごけんとう', meaning: 'consideration (formal)', example: 'ご検討よろしくお願いします。', example_en: 'Please consider this favorably.' },
      { word: '出張', reading: 'しゅっちょう', meaning: 'business trip', example: '来週出張があります。', example_en: 'I have a business trip next week.' },
      { word: '残業', reading: 'ざんぎょう', meaning: 'overtime', example: '今日は残業です。', example_en: 'I am working overtime today.' },
      { word: '有給', reading: 'ゆうきゅう', meaning: 'paid leave', example: '有給を取りたいです。', example_en: 'I want to take paid leave.' },
      { word: '請求書', reading: 'せいきゅうしょ', meaning: 'invoice', example: '請求書を送ってください。', example_en: 'Please send the invoice.' },
      { word: 'よろしくお願いします', reading: 'よろしくおねがいします', meaning: 'please take care of it', example: '今後ともよろしくお願いします。', example_en: 'I look forward to our continued relationship.' },
    ],
  },
  {
    key: 'supermarket', emoji: '🛒', title: 'Supermarket',
    words: [
      { word: '半額', reading: 'はんがく', meaning: 'half price', example: 'このお弁当は半額です。', example_en: 'This bento is half price.' },
      { word: '割引', reading: 'わりびき', meaning: 'discount', example: '二割引になっています。', example_en: 'It is 20% off.' },
      { word: '賞味期限', reading: 'しょうみきげん', meaning: 'best before date', example: '賞味期限を確認してください。', example_en: 'Please check the best before date.' },
      { word: '産地', reading: 'さんち', meaning: 'place of origin', example: '国産の野菜ですか？', example_en: 'Is this domestic produce?' },
      { word: '税込', reading: 'ぜいこみ', meaning: 'tax included', example: 'この値段は税込ですか？', example_en: 'Does this price include tax?' },
      { word: '冷凍', reading: 'れいとう', meaning: 'frozen', example: '冷凍食品はどこですか？', example_en: 'Where are the frozen foods?' },
      { word: '生鮮', reading: 'せいせん', meaning: 'fresh (produce)', example: '生鮮食品売り場はどこですか？', example_en: 'Where is the fresh food section?' },
      { word: 'お総菜', reading: 'おそうざい', meaning: 'prepared foods', example: 'お総菜を買いたいです。', example_en: 'I want to buy prepared foods.' },
      { word: '日用品', reading: 'にちようひん', meaning: 'daily necessities', example: '日用品はどこにありますか？', example_en: 'Where are the daily necessities?' },
      { word: 'セルフレジ', reading: 'serufu reji', meaning: 'self-checkout', example: 'セルフレジを使ってもいいですか？', example_en: 'Can I use the self-checkout?' },
      { word: 'エコバッグ', reading: 'eko baggu', meaning: 'reusable bag', example: 'エコバッグを持っています。', example_en: 'I have a reusable bag.' },
      { word: '肉', reading: 'にく', meaning: 'meat', example: '豚肉はどこですか？', example_en: 'Where is the pork?' },
      { word: '魚', reading: 'さかな', meaning: 'fish', example: '新鮮な魚はありますか？', example_en: 'Do you have fresh fish?' },
      { word: '野菜', reading: 'やさい', meaning: 'vegetables', example: '有機野菜はありますか？', example_en: 'Do you have organic vegetables?' },
      { word: '特売', reading: 'とくばい', meaning: 'special sale', example: '今日の特売は何ですか？', example_en: 'What is on special sale today?' },
    ],
  },
];
